export const K = {
  decks: "simtcg.decks",
  active: "simtcg.activeDeckId",
  save: "simtcg.currentGameState.v3",
  lang: "simtcg.lang",
};

export const REG = ["G", "H", "I", "J"];
export const SUPPORTED_LANGS = new Set(["fr", "en", "es"]);
export const GRID = { cols: 80, rows: 48, cardCols: 10 };

export const mTypes = {
  burn: ["Br", "marker-burn"],
  poison: ["Po", "marker-poison"],
  dmg10: ["10", "marker-dmg10"],
  dmg50: ["50", "marker-dmg50"],
  dmg100: ["100", "marker-dmg100"],
};

export const names = [
  "Voltiguane",
  "Pyrolune",
  "Aqualien",
  "Floraptor",
  "Noctacier",
  "Drakorun",
  "Aetherix",
  "Myradent",
  "Luxoline",
  "Braseclair",
];

export const CATEGORY_BY_LANG = {
  fr: { pokemon: "Pok\u00e9mon", trainer: "Dresseur", energy: "\u00c9nergie" },
  en: { pokemon: "Pokemon", trainer: "Trainer", energy: "Energy" },
  es: { pokemon: "Pok\u00e9mon", trainer: "Entrenador", energy: "Energ\u00eda" },
};

export const gameI18n = {
  fr: {
    "ui.deckAuto": "Deck auto (API)",
    "ui.fullscreen": "Plein ecran",
    "ui.exitFullscreen": "Quitter plein ecran",
    "ui.showHand": "Afficher la main",
    "ui.hideHand": "Masquer la main",
    "ui.draw": "Piocher",
    "ui.setupPrizes": "Poser 6 recompenses",
    "ui.drawPrize": "Piocher recompense",
    "ui.deckEmpty": "Pioche vide",
    "ui.startTitle": "Mode Jeu",
    "ui.startSubtitle": "Choisis un deck puis lance la partie.",
    "ui.multiTitle": "Multijoueur",
    "ui.multiHelp": "Connecte-toi dans Profil pour creer une salle ou rejoindre une salle.",
    "ui.multiSolo": "Solo",
    "ui.multiHost": "Hote",
    "ui.multiGuest": "Invite",
    "ui.multiOffline": "Hors ligne",
    "ui.multiConnected": "Salle connectee",
    "ui.multiWaiting": "Salle en attente",
    "ui.createRoom": "Creer une salle",
    "ui.joinRoom": "Rejoindre",
    "ui.leaveRoom": "Quitter la salle",
    "ui.roomCode": "Code salle",
    "ui.roomPlaceholder": "Code de salle",
    "ui.deckLabel": "Deck",
    "ui.startGame": "Lancer la partie",
    "ui.resumeGame": "Reprendre la partie",
    "ui.returnCatalog": "Retour au catalogue",
    "ui.offlineMode": "Mode hors ligne",
    "ui.offlineReady": "Hors ligne pret",
    "ui.offlineCaching": "Mise en cache...",
    "toast.offlineReady": "Mode hors ligne pret.",
    "toast.offlineFailed": "Echec de l'activation hors ligne.",
    "ui.deckZoneLabel": "Pioche",
    "ui.discardZoneLabel": "Defausse",
    "ui.handTitle": "Main",
    "ui.close": "Fermer",
    "ui.discardTitle": "Defausse",
    "ui.deckTitle": "Pioche",
    "ui.deckCloseTitle": "Fermer la pioche",
    "ui.deckCloseText": "Remelanger la pioche avant de fermer ?",
    "ui.shuffle": "Remelanger",
    "ui.closeNoShuffle": "Fermer sans melanger",
    "ui.deckActionsTitle": "Actions de pioche",
    "ui.viewDeck": "Voir la pioche",
    "ui.markerBagTitle": "Sac de marqueurs",
    "ui.markerBurn": "Brulure",
    "ui.markerPoison": "Poison",
    "ui.retrieve": "Recuperer",
    "ui.emptyDiscard": "Aucune carte dans la defausse.",
    "ui.emptyDeck": "Aucune carte dans la pioche.",
    "hint.toDiscard": "Mettre en defausse",
    "hint.toDeck": "Mettre dans la pioche",
    "hint.toHand": "Mettre en main",
    "hint.placeMat": "Poser sur le tapis",
    "hint.moveMat": "Deplacer sur le tapis",
    "toast.deckLoaded": "Deck selectionne charge.",
    "toast.loadingCards": "Chargement des cartes...",
    "toast.apiFallback": "API indisponible, deck local utilise.",
    "toast.restored": "Partie restauree.",
    "toast.reset": "Partie reinitialisee.",
    "toast.noShuffle": "Pas assez de cartes pour melanger.",
    "toast.shuffled": "Pioche remelangee.",
    "toast.fsRequired": "Plein ecran requis.",
    "toast.noSaved": "Aucune partie a reprendre.",
    "toast.prizesPlaced": "6 recompenses posees.",
    "toast.prizesUnavailable": "Pas assez de cartes pour les recompenses.",
    "toast.noPrizeLeft": "Aucune recompense restante.",
    "toast.multiNeedAuth": "Connecte-toi au profil pour jouer en multijoueur.",
    "toast.multiRoomCreated": "Salle creee.",
    "toast.multiRoomJoined": "Salle rejointe.",
    "toast.multiRoomLeft": "Salle quittee.",
    "toast.multiRoomMissing": "Salle introuvable.",
    "toast.multiSync": "Etat de salle synchronise.",
    "toast.multiLockedObject": "Objet adverse verrouille.",
  },
  en: {
    "ui.deckAuto": "Auto deck (API)",
    "ui.fullscreen": "Fullscreen",
    "ui.exitFullscreen": "Exit fullscreen",
    "ui.showHand": "Show hand",
    "ui.hideHand": "Hide hand",
    "ui.draw": "Draw",
    "ui.setupPrizes": "Set 6 prize cards",
    "ui.drawPrize": "Draw prize",
    "ui.deckEmpty": "Deck empty",
    "ui.startTitle": "Game Mode",
    "ui.startSubtitle": "Choose a deck and start the game.",
    "ui.multiTitle": "Multiplayer",
    "ui.multiHelp": "Sign in on the Profile page to create or join a room.",
    "ui.multiSolo": "Solo",
    "ui.multiHost": "Host",
    "ui.multiGuest": "Guest",
    "ui.multiOffline": "Offline",
    "ui.multiConnected": "Room connected",
    "ui.multiWaiting": "Waiting room",
    "ui.createRoom": "Create room",
    "ui.joinRoom": "Join",
    "ui.leaveRoom": "Leave room",
    "ui.roomCode": "Room code",
    "ui.roomPlaceholder": "Room code",
    "ui.deckLabel": "Deck",
    "ui.startGame": "Start game",
    "ui.resumeGame": "Resume game",
    "ui.returnCatalog": "Back to catalog",
    "ui.offlineMode": "Offline mode",
    "ui.offlineReady": "Offline ready",
    "ui.offlineCaching": "Caching...",
    "toast.offlineReady": "Offline mode is ready.",
    "toast.offlineFailed": "Offline setup failed.",
    "ui.deckZoneLabel": "Deck",
    "ui.discardZoneLabel": "Discard",
    "ui.handTitle": "Hand",
    "ui.close": "Close",
    "ui.discardTitle": "Discard",
    "ui.deckTitle": "Deck",
    "ui.deckCloseTitle": "Close deck view",
    "ui.deckCloseText": "Shuffle deck before closing?",
    "ui.shuffle": "Shuffle",
    "ui.closeNoShuffle": "Close without shuffle",
    "ui.deckActionsTitle": "Deck actions",
    "ui.viewDeck": "View deck",
    "ui.markerBagTitle": "Marker bag",
    "ui.markerBurn": "Burn",
    "ui.markerPoison": "Poison",
    "ui.retrieve": "Take",
    "ui.emptyDiscard": "No cards in discard.",
    "ui.emptyDeck": "No cards in deck.",
    "hint.toDiscard": "Send to discard",
    "hint.toDeck": "Put into deck",
    "hint.toHand": "Put into hand",
    "hint.placeMat": "Place on board",
    "hint.moveMat": "Move on board",
    "toast.deckLoaded": "Selected deck loaded.",
    "toast.loadingCards": "Loading cards...",
    "toast.apiFallback": "API unavailable, local deck used.",
    "toast.restored": "Game restored.",
    "toast.reset": "Game reset.",
    "toast.noShuffle": "Not enough cards to shuffle.",
    "toast.shuffled": "Deck shuffled.",
    "toast.fsRequired": "Fullscreen required.",
    "toast.noSaved": "No saved game to resume.",
    "toast.prizesPlaced": "6 prize cards set.",
    "toast.prizesUnavailable": "Not enough cards for prize setup.",
    "toast.noPrizeLeft": "No prize cards left.",
    "toast.multiNeedAuth": "Sign in on the Profile page to use multiplayer.",
    "toast.multiRoomCreated": "Room created.",
    "toast.multiRoomJoined": "Room joined.",
    "toast.multiRoomLeft": "Room left.",
    "toast.multiRoomMissing": "Room not found.",
    "toast.multiSync": "Room state synced.",
    "toast.multiLockedObject": "Opponent object is locked.",
  },
  es: {
    "ui.deckAuto": "Mazo auto (API)",
    "ui.fullscreen": "Pantalla completa",
    "ui.exitFullscreen": "Salir de pantalla completa",
    "ui.showHand": "Mostrar mano",
    "ui.hideHand": "Ocultar mano",
    "ui.draw": "Robar",
    "ui.setupPrizes": "Colocar 6 premios",
    "ui.drawPrize": "Robar premio",
    "ui.deckEmpty": "Mazo vacio",
    "ui.startTitle": "Modo Juego",
    "ui.startSubtitle": "Elige un mazo y empieza la partida.",
    "ui.multiTitle": "Multijugador",
    "ui.multiHelp": "Inicia sesion en Perfil para crear o unirte a una sala.",
    "ui.multiSolo": "Solo",
    "ui.multiHost": "Anfitrion",
    "ui.multiGuest": "Invitado",
    "ui.multiOffline": "Sin conexion",
    "ui.multiConnected": "Sala conectada",
    "ui.multiWaiting": "Sala en espera",
    "ui.createRoom": "Crear sala",
    "ui.joinRoom": "Unirse",
    "ui.leaveRoom": "Salir de la sala",
    "ui.roomCode": "Codigo",
    "ui.roomPlaceholder": "Codigo de sala",
    "ui.deckLabel": "Mazo",
    "ui.startGame": "Iniciar partida",
    "ui.resumeGame": "Reanudar partida",
    "ui.returnCatalog": "Volver al catalogo",
    "ui.offlineMode": "Modo sin conexion",
    "ui.offlineReady": "Sin conexion listo",
    "ui.offlineCaching": "Guardando cache...",
    "toast.offlineReady": "Modo sin conexion listo.",
    "toast.offlineFailed": "Error en modo sin conexion.",
    "ui.deckZoneLabel": "Mazo",
    "ui.discardZoneLabel": "Descarte",
    "ui.handTitle": "Mano",
    "ui.close": "Cerrar",
    "ui.discardTitle": "Descarte",
    "ui.deckTitle": "Mazo",
    "ui.deckCloseTitle": "Cerrar mazo",
    "ui.deckCloseText": "Mezclar el mazo antes de cerrar?",
    "ui.shuffle": "Mezclar",
    "ui.closeNoShuffle": "Cerrar sin mezclar",
    "ui.deckActionsTitle": "Acciones del mazo",
    "ui.viewDeck": "Ver mazo",
    "ui.markerBagTitle": "Bolsa de marcadores",
    "ui.markerBurn": "Quemadura",
    "ui.markerPoison": "Veneno",
    "ui.retrieve": "Recuperar",
    "ui.emptyDiscard": "No hay cartas en descarte.",
    "ui.emptyDeck": "No hay cartas en el mazo.",
    "hint.toDiscard": "Enviar al descarte",
    "hint.toDeck": "Poner en el mazo",
    "hint.toHand": "Poner en la mano",
    "hint.placeMat": "Colocar en la mesa",
    "hint.moveMat": "Mover en la mesa",
    "toast.deckLoaded": "Mazo seleccionado cargado.",
    "toast.loadingCards": "Cargando cartas...",
    "toast.apiFallback": "API no disponible, mazo local usado.",
    "toast.restored": "Partida restaurada.",
    "toast.reset": "Partida reiniciada.",
    "toast.noShuffle": "No hay suficientes cartas para mezclar.",
    "toast.shuffled": "Mazo mezclado.",
    "toast.fsRequired": "Se requiere pantalla completa.",
    "toast.noSaved": "No hay partida guardada para reanudar.",
    "toast.prizesPlaced": "6 premios colocados.",
    "toast.prizesUnavailable": "No hay cartas suficientes para premios.",
    "toast.noPrizeLeft": "No quedan premios.",
    "toast.multiNeedAuth": "Inicia sesion en Perfil para usar multijugador.",
    "toast.multiRoomCreated": "Sala creada.",
    "toast.multiRoomJoined": "Sala unida.",
    "toast.multiRoomLeft": "Sala cerrada.",
    "toast.multiRoomMissing": "Sala no encontrada.",
    "toast.multiSync": "Estado de sala sincronizado.",
    "toast.multiLockedObject": "Objeto rival bloqueado.",
  },
};
