export const i18n = {
  fr: {
    "app.title": "Sim TCG - Catalogue Standard",
    "app.subtitle": "Affichage des extensions Standard et de leurs cartes via TCGdex.",
    "language.label": "Langue",
    "cards.title": "Catalogue de cartes",
    "cards.subtitle": "Extensions Standard uniquement (liste manuelle G/H/I/J), cartes chargees via TCGdex.",
    "cards.loadSets": "Recharger les cartes Standard",
    "cards.filterLabel": "Type de carte",
    "cards.filterAll": "Tous",
    "cards.filterPokemon": "Pokemon",
    "cards.filterTrainer": "Dresseur",
    "cards.filterEnergy": "Energie",
    "cards.energyTypesLabel": "Types",
    "cards.resultsTitle": "Cartes Standard (G/H/I/J)",
    "cards.searchLabel": "Recherche",
    "cards.searchPlaceholder": "Rechercher une carte...",
    "cards.loadingSets": "Chargement des cartes Standard...",
    "cards.loadingCards": "Chargement des cartes...",
    "cards.loadingTypes": "Chargement des filtres...",
    "cards.error": "Erreur API TCGdex. Reessaie dans quelques secondes.",
    "cards.noCards": "Aucune carte trouvee.",
    "cards.cardsLoaded": "carte(s) chargee(s)",
    "cards.cardsShown": "carte(s) affichee(s)",
    "cards.result.noImage": "Image non disponible",
  },
  en: {
    "app.title": "Sim TCG - Standard Catalog",
    "app.subtitle": "Display Standard-legal sets and their cards through TCGdex.",
    "language.label": "Language",
    "cards.title": "Card catalog",
    "cards.subtitle": "Standard-only sets (manual G/H/I/J list), cards loaded from TCGdex.",
    "cards.loadSets": "Reload Standard cards",
    "cards.filterLabel": "Card type",
    "cards.filterAll": "All",
    "cards.filterPokemon": "Pokemon",
    "cards.filterTrainer": "Trainer",
    "cards.filterEnergy": "Energy",
    "cards.energyTypesLabel": "Types",
    "cards.resultsTitle": "Standard cards (G/H/I/J)",
    "cards.searchLabel": "Search",
    "cards.searchPlaceholder": "Search a card...",
    "cards.loadingSets": "Loading Standard cards...",
    "cards.loadingCards": "Loading cards...",
    "cards.loadingTypes": "Loading filters...",
    "cards.error": "TCGdex API error. Try again in a few seconds.",
    "cards.noCards": "No cards found.",
    "cards.cardsLoaded": "card(s) loaded",
    "cards.cardsShown": "card(s) shown",
    "cards.result.noImage": "No image available",
  },
  es: {
    "app.title": "Sim TCG - Catalogo Standard",
    "app.subtitle": "Muestra expansiones Standard y sus cartas con TCGdex.",
    "language.label": "Idioma",
    "cards.title": "Catalogo de cartas",
    "cards.subtitle": "Solo expansiones Standard (lista manual G/H/I/J), cartas desde TCGdex.",
    "cards.loadSets": "Recargar cartas Standard",
    "cards.filterLabel": "Tipo de carta",
    "cards.filterAll": "Todas",
    "cards.filterPokemon": "Pokemon",
    "cards.filterTrainer": "Entrenador",
    "cards.filterEnergy": "Energia",
    "cards.energyTypesLabel": "Tipos",
    "cards.resultsTitle": "Cartas Standard (G/H/I/J)",
    "cards.searchLabel": "Busqueda",
    "cards.searchPlaceholder": "Buscar una carta...",
    "cards.loadingSets": "Cargando cartas Standard...",
    "cards.loadingCards": "Cargando cartas...",
    "cards.loadingTypes": "Cargando filtros...",
    "cards.error": "Error de API TCGdex. Intentalo de nuevo en segundos.",
    "cards.noCards": "No se encontraron cartas.",
    "cards.cardsLoaded": "carta(s) cargada(s)",
    "cards.cardsShown": "carta(s) mostrada(s)",
    "cards.result.noImage": "Imagen no disponible",
  },
};

export const regulationMarks = ["G", "H", "I", "J"];

export const typeDefinitions = {
  grass: {
    fr: { label: "Plante", api: "Plante" },
    en: { label: "Grass", api: "Grass" },
    es: { label: "Planta", api: "Planta" },
  },
  fire: {
    fr: { label: "Feu", api: "Feu" },
    en: { label: "Fire", api: "Fire" },
    es: { label: "Fuego", api: "Fuego" },
  },
  water: {
    fr: { label: "Eau", api: "Eau" },
    en: { label: "Water", api: "Water" },
    es: { label: "Agua", api: "Agua" },
  },
  lightning: {
    fr: { label: "Électrique", api: "Électrique" },
    en: { label: "Lightning", api: "Lightning" },
    es: { label: "Rayo", api: "Rayo" },
  },
  psychic: {
    fr: { label: "Psy", api: "Psy" },
    en: { label: "Psychic", api: "Psychic" },
    es: { label: "Psíquico", api: "Psíquico" },
  },
  fighting: {
    fr: { label: "Combat", api: "Combat" },
    en: { label: "Fighting", api: "Fighting" },
    es: { label: "Lucha", api: "Lucha" },
  },
  darkness: {
    fr: { label: "Obscure", api: "Obscurité" },
    en: { label: "Darkness", api: "Darkness" },
    es: { label: "Oscura", api: "Oscura" },
  },
  metal: {
    fr: { label: "Métal", api: "Métal" },
    en: { label: "Metal", api: "Metal" },
    es: { label: "Metálica", api: "Metálica" },
  },
  dragon: {
    fr: { label: "Dragon", api: "Dragon" },
    en: { label: "Dragon", api: "Dragon" },
    es: { label: "Dragón", api: "Dragón" },
  },
  colorless: {
    fr: { label: "Incolore", api: "Incolore" },
    en: { label: "Colorless", api: "Colorless" },
    es: { label: "Incolora", api: "Incolora" },
  },
};

export const typeOrder = ["grass", "fire", "water", "lightning", "psychic", "fighting", "darkness", "metal", "dragon", "colorless"];
export const basicEnergyTypeKeys = [...typeOrder];
export const energyTypeColors = {
  grass: { bg: "#4e9f4f", fg: "#ffffff" },
  fire: { bg: "#d4552d", fg: "#ffffff" },
  water: { bg: "#2d7fcf", fg: "#ffffff" },
  lightning: { bg: "#d6b332", fg: "#1b1b1b" },
  psychic: { bg: "#8c57c2", fg: "#ffffff" },
  fighting: { bg: "#a2643a", fg: "#ffffff" },
  darkness: { bg: "#3d3d3d", fg: "#ffffff" },
  metal: { bg: "#8a9aa6", fg: "#1b1b1b" },
  dragon: { bg: "#cc8a24", fg: "#ffffff" },
  colorless: { bg: "#c7bca8", fg: "#1b1b1b" },
};
